services:
  - docker

jobs:
  include:
    - stage: build
      script: docker build -f bionic/Dockerfile -t $DOCKER_USERNAME/texlive:bionic .
      script: docker build -f focal/Dockerfile -t $DOCKER_USERNAME/texlive:focal .
    - stage: login
      script: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin > /dev/null 2>&1
    - stage: deploy
      script: docker push $DOCKER_USERNAME/texlive:bionic
      script: docker push $DOCKER_USERNAME/texlive:focal
